apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-dockerignore
spec:
  selector:
    matchLabels:
      app: tilt-dockerignore
  template:
    metadata:
      labels:
        app: tilt-dockerignore
    spec:
      containers:
      - name: tilt-dockerignore
        image: tilt-dockerignore
        ports:
        - containerPort: 8101
          name: http
